package javaapplication1;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class catalogo extends javax.swing.JFrame {

    ImageIcon Imagen [] = new ImageIcon[6];
    public catalogo() {
        initComponents();
        this.setTitle("Catalogo de plantas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(814, 660));
        setMinimumSize(new java.awt.Dimension(814, 660));
        setPreferredSize(new java.awt.Dimension(814, 660));
        getContentPane().setLayout(null);

        jLabel1.setText("Catálogo de plantas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(366, 11, 140, 14);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(18, 579, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 36, 220, 175);
        jLabel2.getAccessibleContext().setAccessibleName("");

        jLabel3.setText("Nombre: Albahaca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(18, 229, 160, 14);

        jLabel4.setText("Temperatura: 20° ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(18, 249, 140, 14);

        jLabel5.setText("Humedad: 8.2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(18, 269, 150, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(287, 36, 220, 175);
        jLabel6.getAccessibleContext().setAccessibleName("");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(559, 36, 220, 175);
        jLabel10.getAccessibleContext().setAccessibleName("");

        jLabel11.setText("Nombre: Menta");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(559, 229, 100, 14);

        jLabel12.setText("Temperatura: 20°");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(559, 249, 150, 14);

        jLabel13.setText("Humedad: 6.5");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(559, 269, 120, 14);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(18, 321, 228, 175);
        jLabel14.getAccessibleContext().setAccessibleName("");

        jLabel24.setText("Nombre: Tomillo");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(287, 229, 130, 14);

        jLabel25.setText("Temperatura: 25°");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(287, 249, 120, 14);

        jLabel26.setText("Humedad: 7.0");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(287, 269, 100, 14);

        jLabel15.setText("Nombre: Estragon");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(18, 514, 130, 14);

        jLabel16.setText("Temperatura: 15°");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(18, 534, 130, 14);

        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(36, 39, 14, 14);

        jLabel18.setText("Humedad: 6.0");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(18, 554, 130, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(287, 321, 220, 175);
        jLabel7.getAccessibleContext().setAccessibleName("");

        jLabel8.setText("Nombre: Oregano");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(287, 514, 140, 14);

        jLabel9.setText("Temperatura: 25°");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(287, 534, 120, 14);

        jLabel19.setText("Humedad: 8.13");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(287, 554, 120, 14);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(559, 323, 220, 173);
        jLabel20.getAccessibleContext().setAccessibleName("");

        jLabel21.setText("Nombre: Romero");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(559, 514, 140, 14);

        jLabel22.setText("Temperatura: 25°");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(559, 534, 150, 14);

        jLabel23.setText("Humedad: 6.5");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(559, 554, 120, 14);

        jButton2.setText("Ver General");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 580, 100, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c1.jpg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jLabel27.setMaximumSize(new java.awt.Dimension(700, 900));
        jLabel27.setMinimumSize(new java.awt.Dimension(700, 900));
        jLabel27.setPreferredSize(new java.awt.Dimension(700, 900));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 800, 640);
        jLabel27.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal boton_regreso = new Principal();
        boton_regreso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        general_catalogo boton_sig = new general_catalogo();
        boton_sig.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    String consulta_catalogo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
